### ISSUE TITLE
workflow_dispatch

### ISSUE THREAD

**Issue by Jhon-Mosk** [saadmk11/changelog-ci#105]
## Describe the bug
When I try to run an action manually, I end up with an error.
![image](https://github.com/saadmk11/changelog-ci/assets/40711760/9b69e958-9687-423c-9459-e46045859a04)
I tried to introduce different options: v1.0.0; 0.0.0; release v1.0.0; release_version v1.0.0. 

## Your Environment

**Workflow Run URL **
repository is private

```yml
name: Changelog CI

on:
  pull_request:
    types: [opened]

  # Optionally you can use `workflow_dispatch` to run Changelog CI Manually
  workflow_dispatch:
    inputs:
      release_version:
        description: "Set Release Version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/changelog-ci
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: .github/workflows/changelog-config.json
```

**Contents of Changelog-CI Configuration File (If Applicable):**
```json
{
  "changelog_type": "commit_message",
  "header_prefix": "Version:",
  "commit_changelog": true,
  "comment_changelog": true,
  "include_unlabeled_changes": true,
  "unlabeled_group_title": "Unlabeled Changes",
  "exclude_labels": ["bot", "dependabot", "ci"],
  "group_config": [
    {
      "title": "Bug Fixes",
      "labels": ["bug", "bugfix"]
    },
    {
      "title": "Code Improvements",
      "labels": ["improvements", "enhancement"]
    },
    {
      "title": "New Features",
      "labels": ["feature"]
    },
    {
      "title": "Documentation Updates",
      "labels": ["docs", "documentation", "doc"]
    }
  ]
}
```

## Expected behavior
I expect that when I manually run the action, it will create a changelog with all the commits and pull requests that are in the main branch from the previous release with the version that I specified.

## Actual behavior
Error: `release_version` input must be provided to generate Changelog. Please Check the Documentation for more details. Aborting Changelog Generation
