### ISSUE TITLE
Dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by tomer-ds** [saadmk11/changelog-ci#93]
## Describe the bug
When attempting to build changelog on Release branch I get an error 
`fatal: detected dubious ownership in repository at '/github/workspace'`

## Your Environment

**Contents of Your Changelog-CI Workflow File (.yaml File):**
```yaml
name: Changelog CI

on:
  push:
    branches:
      - hotfix/*
      - release/*
    paths-ignore:
      - "*.md"

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.11.1"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Run Changelog CI
        id: changelog-ci
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          config_file: changelog-config.yaml
          release_version: ${{ steps.gitversion.outputs.majorMinorPatch }}
          github_token: ${{ secrets.ACTIONS_AUTH_TOKEN }}

      - name: Get Changelog Output
        run: |
          echo "${{ steps.changelog-ci.outputs.changelog }}"
          echo "${{ steps.changelog-ci.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY

```

**Contents of Changelog-CI Configuration File (If Applicable):**
```yaml
changelog_type: "commit_message"
header_prefix: "Version:"
commit_changelog: true
comment_changelog: false
include_unlabeled_changes: true
unlabeled_group_title: "Changes"
pull_request_title_regex: ".*"
version_regex: ".*"
group_config:
  - title: Bug Fixes
    labels:
      - bug
      - bugfix
  - title: Code Improvements
    labels:
      - improvements
      - enhancement
  - title: New Features
    labels:
      - feature
  - title: Updates
    labels:
      - update
  - title: Dependencies
    labels:
      - dependencies
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc

```

## Expected behavior
Changelog will be generated successfully and committed to the release branch.

## Actual behavior
Errors about dubious ownership and lack of git directory

## Additional context

![image](https://user-images.githubusercontent.com/30149311/222238381-43e31693-9873-47ef-8493-52b8ab5f420d.png)
